### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by kutaki3** [Geigerkind/vb_positions#1]
Volleyball rotation goes clockwise not counter-clockwise.

**Comment by kutaki3** [comment]
![image](https://user-images.githubusercontent.com/121305647/209362990-b3e8d473-cfba-45e5-87c4-047bb09ce1cb.png)

**Comment by tdymel** [comment]
Hello!
Thank you for your feedback! I had been on holidays, so I wasnt able to reply.
What you say is correct. This app does not have strict rotation in that sense. Let me explain:
If you create an actor, you tell it what position the actor has relative to whoever is on P1. Usually your setter. The rotations you set are meant in absolute way: "Rotation of actors relative to actor in P1 if he moved to PX".

Does that solve your issue? If not please elaborate a little bit more :)

**Comment by tdymel** [comment]
Closing it, because of no response :)
